#ifndef BOARD_PROFILE_ESP32S2_H
#define BOARD_PROFILE_ESP32S2_H

#define BOARD_PROFILE_NAME "esp32s2"
#define BOARD_HAS_ETH 0
#define BOARD_DEFAULT_NETIF_MODE 1  // Wi-Fi only
#define BOARD_DEFAULT_SIREN_GPIO 17
#define BOARD_DEFAULT_TRIGGER_GPIO 16
#define BOARD_DEFAULT_STATUS_LED_GPIO 15
#define BOARD_BOOT_GPIO 0
#define BOARD_HAS_VBAT_ADC 1
#define BOARD_DEFAULT_VBAT_ADC_PIN 4
#define BOARD_DEFAULT_ADC_ATTENUATION ADC_11db

#endif
