#ifndef BOARD_PROFILE_PRODINO_ESP32_ETH_H
#define BOARD_PROFILE_PRODINO_ESP32_ETH_H

#define BOARD_PROFILE_NAME "prodino_esp32_eth"
#define BOARD_DEFAULT_NETIF_MODE 2
#define BOARD_DEFAULT_SIREN_GPIO 25
#define BOARD_DEFAULT_TRIGGER_GPIO 33
#define BOARD_DEFAULT_STATUS_LED_GPIO 2
#define BOARD_HAS_VBAT_ADC 1
#define BOARD_DEFAULT_VBAT_ADC_PIN 34
#define BOARD_DEFAULT_ADC_ATTENUATION ADC_11db

// Typical LAN8720 defaults used by ESP32 Ethernet boards.
#define BOARD_ETH_PHY_TYPE ETH_PHY_LAN8720
#define BOARD_ETH_PHY_ADDR 1
#define BOARD_ETH_MDC_PIN 23
#define BOARD_ETH_MDIO_PIN 18
#define BOARD_ETH_POWER_PIN -1
#define BOARD_ETH_CLK_MODE ETH_CLOCK_GPIO17_OUT

#endif
