#ifndef BOARD_PROFILE_ESP32C2_H
#define BOARD_PROFILE_ESP32C2_H

#define BOARD_PROFILE_NAME "esp32c2"
#define BOARD_HAS_ETH 0
#define BOARD_DEFAULT_NETIF_MODE 1  // Wi-Fi only
#define BOARD_DEFAULT_SIREN_GPIO 4
#define BOARD_DEFAULT_TRIGGER_GPIO 3
#define BOARD_DEFAULT_STATUS_LED_GPIO 2
#define BOARD_HAS_VBAT_ADC 1
#define BOARD_DEFAULT_VBAT_ADC_PIN 0
#define BOARD_DEFAULT_ADC_ATTENUATION ADC_11db

#endif
