#ifndef BOARD_PROFILE_ESP32_H
#define BOARD_PROFILE_ESP32_H

#define BOARD_PROFILE_NAME "esp32"
#define BOARD_HAS_ETH 0
#define BOARD_DEFAULT_NETIF_MODE 1  // Wi-Fi only (classic ESP32 has no on-board Ethernet PHY)
#define BOARD_DEFAULT_SIREN_GPIO 25
#define BOARD_DEFAULT_TRIGGER_GPIO 33
#define BOARD_DEFAULT_STATUS_LED_GPIO 2
#define BOARD_HAS_VBAT_ADC 1
#define BOARD_DEFAULT_VBAT_ADC_PIN 34
#define BOARD_DEFAULT_ADC_ATTENUATION ADC_11db

#endif
